0.1.1
OP-TED/eForms-SDK pull request #1
Opened 2021-04-20 17:02 UTC by pdonohoe

Merge 0.1.1 to Master.
Changes to 0.1.1:
Changed eForms_Schemas_Usage.docx title page from "Version 1.1 – May 2020" to "May 2020"
Changed examples notices cbc:CustomizationID from "eforms-1.0" to "eforms-sdk-0.1.1"

2021-04-20 17:12 UTC, guimath-ec commented on README.md
> +- the major version number changes only if the new schema or schematron files break backward-compatibility
I understand for the schema but not for the Schematron, what does it mean that a change in the schematron breaks the backward compatibility?

2021-04-20 18:39 UTC, pdonohoe commented on README.md
> +- the major version number changes only if the new schema or schematron files break backward-compatibility
I think the wording here is not very good. What it means is that a notice XML that was valid against the previous version of the schematron, is not valid against the new version of the schematron. OR that a notice XML that was not valid against the previous version of the schematron, is valid against the new version of the schematron.

2021-04-20 18:43 UTC, pdonohoe commented on README.md
> +- the major version number changes only if the new schema or schematron files break backward-compatibility
Would this be better?
- the major version number changes only if the new schema or schematron files change the validity of notice XML files.

2021-04-20 19:10 UTC, mgtix commented on README.md
> +- the major version number changes only if the new schema or schematron files break backward-compatibility
Not really, do we really want to increment a major release version each time we create an additional rule?

2021-04-21 03:00 UTC, guimath-ec commented on README.md
> +- the major version number changes only if the new schema or schematron files break backward-compatibility
Not really, do we really want to increment a major release version each time we create an additional rule? I'm scared it will happen a lot, I see such quality improvement as a continuous process.

2021-04-21 06:30 UTC, pdonohoe commented on README.md
> +- the major version number changes only if the new schema or schematron files break backward-compatibility
Doesn't that depend on how often we create a release?

2021-04-21 06:49 UTC, guimath-ec commented on README.md
> +- the major version number changes only if the new schema or schematron files break backward-compatibility
It does but I'm scared that with the proposed versioning logic, we would create a lot of tiny "major" releases just to add few new Schematron rules.

2021-04-21 10:04 UTC, rousso requested changes
This commit updates the UBL XSDs. Since we are only re-distributing them for the convenience of our users, we should not modify the Oasis files directly. It appears to me that these changes were done with a text editor. Therefore I suggest that a new commit replaces these files with direct copies from the Oasis UBL distribution site.

2021-04-21 12:20 UTC, bertrand-lorentz reviewed
The new value of "cbc:CustomizationID" should be "eforms-sdk-0.1"
The patch version number is not relevant here.

2021-04-26 14:12 UTC, bertrand-lorentz commented
With the latest commit, OK for me. 👍

2021-04-27 15:50 UTC, rousso approved these changes
Looks good to me.

2021-04-27 16:29 UTC, guimath-ec approved these changes

2021-04-28 09:05 UTC, YvesJo approved these changes

2021-04-28 09:09 UTC, bertrand-lorentz approved these changes

2021-04-28 10:57 UTC, merged