Update generated files and examples
OP-TED/eForms-SDK pull request #133
Opened 2022-10-05 16:38 UTC by bertrand-lorentz

Large batch of updates to the generated files, and to the examples to adapt for those changes.
This will be included in the upcoming 1.2.0 release.

You're probably better off looking at individual commits, and not the whole diff, as its quite large.

2022-10-05 16:49 UTC, rouschr approved these changes
timeperiod stuff looks so Ok for me

2022-10-05 22:33 UTC, rousso requested changes
Apart from the inconsistencies in the database version used to generate everything (some of which I pointed out in my comments), I do not see any other issue. 

I understand that this had to be an iterative process and I assume that we will eventually bump the MDD version to 1.2.0 and regenerate everything with MDC in one go.

2022-10-05 22:33 UTC, rousso commented on fields/fields.json
> +    "version" : "1.1.12",
I think we should go to  MDD version 1.2.0

2022-10-05 22:33 UTC, rousso commented on schematrons/dynamic/complete-validation.sch
> +<!--File generated from metadata database version 1.1.14 created on the 2022-09-21T13:34:47.-->
This database version (!.1.14) is different from the version used to create fields.json (1.1.12)

2022-10-05 22:33 UTC, rousso commented on schematrons/dynamic/validation-stage-2a.sch
> +<!--File generated from metadata database version 1.1.20 created on the 2022-09-21T17:25:19.-->
1.1.20 != 1.1.14 != 1.1.12

2022-10-06 13:20 UTC, bertrand-lorentz commented
The metadata database version will be indeed updated to 1.2.0 for all files as part of the release branch.

2022-10-06 13:21 UTC, merged