Prepare release of SDK 1.6.0
OP-TED/eForms-SDK pull request #347
Opened 2023-02-17 13:49 UTC by bertrand-lorentz

2023-02-17 17:07 UTC, rouschr requested changes
I request changes because of that one link.

2023-02-17 17:07 UTC, rouschr commented on CHANGELOG.md
> +A comprehensive list of changes between SDK 1.5.1 and SDK 1.6.0 can be seen at <https://github.com/OP-TED/eForms-SDK/compare/1.5.1...1.5.0>
I suppose the URL must be updated to 1.5.1...1.6.0

2023-02-17 17:07 UTC, rouschr commented on CHANGELOG.md
> +* The content of codelists were updated.
I think it would be a bit better to write: 
"The content of codelists was updated" (The content = it = it was updated)

2023-02-20 08:13 UTC, bertrand-lorentz commented on CHANGELOG.md
> +A comprehensive list of changes between SDK 1.5.1 and SDK 1.6.0 can be seen at <https://github.com/OP-TED/eForms-SDK/compare/1.5.1...1.5.0>
Fixed, thanks !

2023-02-20 08:13 UTC, bertrand-lorentz commented on CHANGELOG.md
> +* The content of codelists were updated.
Corrected.

2023-02-20 09:48 UTC, YvesJo submitted a review, later dismissed

2023-02-20 12:26 UTC, pdonohoe approved these changes

2023-02-20 17:19 UTC, YvesJo submitted a review, later dismissed

2023-02-20 21:22 UTC, pdonohoe approved these changes

2023-02-23 10:42 UTC, YvesJo submitted a review, later dismissed

2023-03-03 15:41 UTC, ferrakaop approved these changes

2023-03-06 08:30 UTC, rouschr approved these changes

2023-03-06 09:01 UTC, merged