TEDEFO-2124 add OPT-060-Lot after OPT-070-Lot in NTD 7 to 22,38,39,40,CEI
OP-TED/eForms-SDK pull request #425
Opened 2023-04-21 12:23 UTC by rouschr

It was branched from origin/update_sdk_1.7.0
And the destination is origin/update_sdk_1.7.0

2023-04-21 13:18 UTC, rouschr commented
For PR see:
https://github.com/OP-TED/eForms-SDK/pull/425

2023-04-24 08:19 UTC, rousso requested changes
Please fix the two comments first.

2023-04-24 08:19 UTC, rousso commented on .ted/tedweb/search-metadata.json
This commit is not relevant to the ticket, so we need to remove it from this PR

2023-04-24 08:19 UTC, rousso commented on notice-types/15.json
> +        }, {
This is duplicate. Needs to be fixxed.

2023-04-24 09:06 UTC, rouschr commented
I will close this PR as there was a commit that comes from another branch, it will be cleaner to redo this PR.

2023-04-24 09:06 UTC, closed without merging