Prepare release of SDK 1.6.1
OP-TED/eForms-SDK pull request #463
Opened 2023-05-12 14:20 UTC by bertrand-lorentz

FYI, the diff for translations is quite large, in particular for rule_en.xml.

2023-05-22 16:14 UTC, pdonohoe approved these changes
There are no fields used in the EFX templates in prepare/1.6.1 that are not defined in fields.json in release/1.3.4 :)

2023-05-25 11:59 UTC, bertrand-lorentz commented
View templates were all successfully compiled manually. This confirms their syntax is valid and they do not reference any node or field that does not exist in this version.

2023-05-26 23:09 UTC, rousso commented on translations/auxiliary_ga.xml
> +<comment>auxiliary in Irish. File generated from metadata database.</comment>
The filename has _ga which I assume stands for Galician. The comment was changed from Galician to Irish. The actual labels are in Irish. Something is wrong with this file.

2023-05-26 23:12 UTC, rousso commented on translations/business-term_ga.xml
> +<comment>business-term in Irish. File generated from metadata database.</comment>
Same here. Is the filename correct?

2023-05-26 23:35 UTC, rousso requested changes
Apart from the *_ga.xml files in translations where the filename seems wrong, everything else looks good to me. We should check the filename though because the content of those files is in Irish so I would expect to see *_ie.xml

2023-05-26 23:35 UTC, rousso commented on translations/view_ga.xml
Check if the filename is correct. "ga" does not seem to be a two letter code for Irish to me.

2023-05-26 23:35 UTC, rousso commented on translations/rule_ga.xml
Check if the filename is correct. "ga" does not seem to be a two letter code for Irish to me.

2023-05-26 23:35 UTC, rousso commented on translations/notice_ga.xml
Check if the filename is correct. "ga" does not seem to be a two letter code for Irish to me.

2023-05-26 23:35 UTC, rousso commented on translations/group_ga.xml
Check if the filename is correct. "ga" does not seem to be a two letter code for Irish to me.

2023-05-26 23:35 UTC, rousso commented on translations/field_ga.xml
Check if the filename is correct. "ga" does not seem to be a two letter code for Irish to me.

2023-05-26 23:35 UTC, rousso commented on translations/codelist_ga.xml
Check if the filename is correct. "ga" does not seem to be a two letter code for Irish to me.

2023-05-30 08:21 UTC, bertrand-lorentz commented
> Apart from the *_ga.xml files in translations where the filename seems wrong, everything else looks good to me. We should check the filename though because the content of those files is in Irish so I would expect to see *_ie.xml

The 2 letter code for Irish is "ga". So no problem here.
So as agreed with Yannis I'm merging this.
Note: checks are failing because they are not target for this version of the SDK, which causes false alerts.

2023-05-30 08:22 UTC, merged