Prepare release of SDK 1.5.3
OP-TED/eForms-SDK pull request #469
Opened 2023-05-16 13:12 UTC by bertrand-lorentz

2023-05-25 11:59 UTC, bertrand-lorentz commented
View templates were all successfully compiled manually. This confirms their syntax is valid and they do not reference any node or field that does not exist in this version.

2023-05-26 23:36 UTC, rousso commented on translations/auxiliary_ga.xml
Same issue with review of 1.6.1. The filename seems wrong.

2023-05-26 23:40 UTC, rousso requested changes
Same issues with review of 1.6.1. The indicated filenames seem wrong.

2023-05-26 23:40 UTC, rousso commented on translations/business-term_ga.xml
Same issue with review of 1.6.1. The filename seems wrong.

2023-05-26 23:40 UTC, rousso commented on translations/code_ga.xml
Same issue with review of 1.6.1. The filename seems wrong.

2023-05-26 23:40 UTC, rousso commented on translations/view_ga.xml
Same issue with review of 1.6.1. The filename seems wrong.

2023-05-26 23:40 UTC, rousso commented on translations/rule_ga.xml
Same issue with review of 1.6.1. The filename seems wrong.

2023-05-26 23:40 UTC, rousso commented on translations/notice_ga.xml
Same issue with review of 1.6.1. The filename seems wrong.

2023-05-26 23:40 UTC, rousso commented on translations/group_ga.xml
Same issue with review of 1.6.1. The filename seems wrong.

2023-05-26 23:40 UTC, rousso commented on translations/field_ga.xml
Same issue with review of 1.6.1. The filename seems wrong.

2023-05-26 23:40 UTC, rousso commented on translations/codelist_ga.xml
Same issue with review of 1.6.1. The filename seems wrong.

2023-05-30 08:53 UTC, merged