Added/updated README files and CHANGELOG for SDK 2.
OP-TED/eForms-SDK pull request #504
Opened 2023-06-03 16:18 UTC by rousso

2023-06-05 08:49 UTC, bertrand-lorentz requested changes

2023-06-05 08:49 UTC, bertrand-lorentz commented on CHANGELOG.md
> +:heavy_check_mark: **No other breaking changes** in the metadata provided have been introduced in SDK 2. With the exception of the  updates necessary for EFX parsers, metadata driven applications bui
Based on the paragraph below ("Future pre-release versions might introduce further breaking changes."), this statement is only valid for SDK 2.0.0-alpha.1, so this phrase should mention that version, and not "SDK 2" in general.

2023-06-05 08:49 UTC, bertrand-lorentz commented on README.md
> +We encourage users to test the pre-release version of the eForms SDK and provide feedback to help us improve the final release.
We should mention how to provide feedback.

2023-06-05 08:49 UTC, bertrand-lorentz commented on codelists/README.md
> +:heavy_check_mark: **No breaking changes** in the metadata provided in this folder have been introduced by SDK 2. Metadata driven applications built on top of SDK 1 should be able to use the metadata
As this just mentions "SDK 2", it could be understood as being also applicable (a promise) for SDK 2.0.0.
If it is not the case, it should be indicated more clearly.
Same comment for this phrase in the other README.md files.

2023-06-05 12:51 UTC, NPJ-OP-LUX commented
Although I am not yet familiar with the content but the readme.md information seems thorough and there is a version for each significant folder. The details suggested by Bertrand are relevant/ important and should be included. The information on the readme.md files and the information on the TED Documentation site complement each other well.

From: Yannis Rousochatzakis ***@***.***>
Sent: Saturday, June 3, 2023 6:22 PM
To: OP-TED/eForms-SDK ***@***.***>
Cc: PATERSON-JONES Nicole Anne (OP-EXT) ***@***.***>; Review requested ***@***.***>
Subject: Re: [OP-TED/eForms-SDK] Added/updated README files and CHANGELOG for SDK 2. (PR #504)


@rousso<https://urldefense.com/v3/__https:/github.com/rousso__;!!DOxrgLBm!F19-7PAVY7Wsmm-VqC1_O_q6sdPKd_jHU-m3Un8hTc3BmaC8NxdUa7xFY9L33lIU3aXb2gy_87rQ1F_DBO8MIIhuTZFaE_vwjEkr0WS38dm2Ig$> requested your review on: #504<https://urldefense.com/v3/__https:/github.com/OP-TED/eForms-SDK/pull/504__;!!DOxrgLBm!F19-7PAVY7Wsmm-VqC1_O_q6sdPKd_jHU-m3Un8hTc3BmaC8NxdUa7xFY9L33lIU3aXb2gy_87rQ1F_DBO8MIIhuTZFaE_vwjEkr0WQ3eav7ZQ$> Added/updated README files and CHANGELOG for SDK 2..

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/OP-TED/eForms-SDK/pull/504*event-9421832283__;Iw!!DOxrgLBm!F19-7PAVY7Wsmm-VqC1_O_q6sdPKd_jHU-m3Un8hTc3BmaC8NxdUa7xFY9L33lIU3aXb2gy_87rQ1F_DBO8MIIhuTZFaE_vwjEkr0WRrl0UDlA$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/A67N3S5SQO7LGEAIBVVS4V3XJNQEDANCNFSM6AAAAAAYZL7MDE__;!!DOxrgLBm!F19-7PAVY7Wsmm-VqC1_O_q6sdPKd_jHU-m3Un8hTc3BmaC8NxdUa7xFY9L33lIU3aXb2gy_87rQ1F_DBO8MIIhuTZFaE_vwjEkr0WTGnmkZMw$>.
You are receiving this because your review was requested.Message ID: ***@***.******@***.***>>

2023-07-17 09:42 UTC, rouschr commented on README.md
> +We encourage users to test the pre-release version of the eForms SDK and provide feedback to help us improve the final release.
I created a ticket, this is a valid point in general and many projects have a few chapters about where to ask or discuss about the project as this helps a bit. I created this ticket and I am ready to do something if we can agree: https://citnet.tech.ec.europa.eu/CITnet/jira/browse/TEDEFO-2471

2026-03-26 11:04 UTC, bertrand-lorentz approved these changes

2026-03-26 11:05 UTC, merged