TEDEFO-1065 export of various files with the new labels.
OP-TED/eForms-SDK pull request #55
Opened 2022-07-27 13:08 UTC by rouschr

This allows to compare the new vs old labels.

2022-07-27 13:13 UTC, rouschr commented
Let me know if there are too many files.
I could restrict this to just the translations, codelists and some of the index mapping files.

2022-07-27 13:20 UTC, bertrand-lorentz requested changes
The translations for "business-term" do not have the expected filename. Currently it is:
translations/business_term_en.xml

It should be:
translations/business-term_en.xml

I have a fix for this in MDC, I'll submit it shortly.

2022-07-27 14:03 UTC, rouschr commented
I reexported the translations with the correct filenames after merging the MDC fix.

2022-07-27 15:10 UTC, bertrand-lorentz reviewed
It would have been better to have one commit per type of file, as some files have other changes included. For example fields.json has the move of the XML structure.

2022-07-27 15:10 UTC, bertrand-lorentz commented on translations/expression_en.xml
> +<entry key="expression|text|1">the value chosen for the indicator of BT-740-Procedure-Buyer is 'NO'</entry>
I'm not sure we had decide to go from `expression|description|...` to `expression|text|...`
Please confirm that it was intended.

2022-07-27 23:00 UTC, rousso approved these changes

2022-07-27 23:05 UTC, rousso requested changes
I agree with Bertrand. There are important files missing here wheres some files are not really changed.
The codelists for example are not changed essentially.
The EFX view templates are essential and need to be brought to the develop branch of the SDK.
I propose to close this PR without merging and to separate PRs per file type so that we can have more control as Bertrand suggests.

2022-07-27 23:06 UTC, rousso commented on translations/expression_en.xml
> +<entry key="expression|text|1">the value chosen for the indicator of BT-740-Procedure-Buyer is 'NO'</entry>
Indeed we did not decide to go from expression description to expression text. 
We should remain with expression|description.

2022-07-28 07:39 UTC, rouschr commented on translations/expression_en.xml
> +<entry key="expression|text|1">the value chosen for the indicator of BT-740-Procedure-Buyer is 'NO'</entry>
I do not see any of my SQL which could have done this:
UPDATE label set asset_type = 'expression' where asset_type = 'condition';
I did not change the description to text.

2022-07-28 07:41 UTC, closed without merging