schematrons: Add manual check of notice id on TED website (TEDEFO-1994)
OP-TED/eForms-SDK pull request #550
Opened 2023-06-28 08:17 UTC by bertrand-lorentz

In dynamic mode, use the TED website search API to search for a notice with the id of the notice being validated, and test that none is found.

This is a temporary partial check, as this only looks at published notices. The full check should also look at notices in the publication process.

2023-06-28 08:20 UTC, bertrand-lorentz commented
This has been tested by uploading custom Schematron with this change to CVS in our acceptance environment.
If notice id is "new" : no failure.
If notice id is set to an existing id on TED, the SVRL response contains:
```xml
<svrl:failed-assert location="/pin:PriorInformationNotice/cbc:ID" test="matches(function($id) { fn:unparsed-text(replace('https://ted.europa.eu/api/v3.0/notices/search?q=notice-identifier=[##NOTICE_ID##]&amp;scope=3', '##NOTICE_ID##', $id)) }(normalize-space(.)), '&quot;total&quot;\s*:\s*0')" role="ERROR">
        <svrl:text>
		There is already a published notice with this identifier.
	</svrl:text>
</svrl:failed-assert>
```

2023-06-29 08:39 UTC, pdonohoe requested changes
Assert test is not valid xpath, $searchNotice is of type text:
XPTY0019: The result of a step (other than the last step) in a path expression may not contain atomic values 
Change to:
matches(normalize-space($searchNotice), '&quot;total&quot;\s*:\s*0')
I converted this to XSLT and tested, it works fine.

2023-06-29 08:56 UTC, bertrand-lorentz commented
I don't understand: searchNotice is a function, defined in the "let" above, which takes a parameter. And we want to pass in this parameter the value in "/*/cbc:ID" (selected via the rule context).
So I don't see how your proposed change would do what we want

2023-06-29 09:52 UTC, pdonohoe commented
Sorry, my mistake, it's fine. Explanation:

I had to change the derived XSLT to get it to work in XMLSpy, and that caused my problem, as I converted the function to an expression. 
I then converted your schematron to XSLT and tried to run it:
a) using the command line and Saxon, the XSLT was valid, and ran successfully, with the right result
b) using XMLSpy, I got the following error:
XPST0003: The expression around 'function($id) { fn:unparsed' is not a valid instance of the XPath grammar
XMLSpy uses it's own "RaptorXML XSLT engine", which I think isn't fully XSLT 2 compliant :(

2023-06-29 09:53 UTC, pdonohoe approved these changes

2023-06-29 11:20 UTC, merged