Prepare/1.9.3
OP-TED/eForms-SDK pull request #920
Opened 2024-04-26 13:24 UTC by yfanti

2024-04-29 20:19 UTC, ferrakaop approved these changes

2024-04-30 09:51 UTC, pdonohoe requested changes
Changes to view-templates/28.efx Results section should not be merged

2024-04-30 12:47 UTC, pdonohoe approved these changes

2024-04-30 12:57 UTC, bertrand-lorentz commented
Changes to the "LotResult" section of view-templates/28.efx were reverted in added commit 7e7d320.

2024-05-02 08:33 UTC, bertrand-lorentz approved these changes

2024-05-02 08:42 UTC, merged