Prepare release of SDK 1.8.3
OP-TED/eForms-SDK pull request #921
Opened 2024-04-26 14:30 UTC by yfanti

2024-04-29 20:23 UTC, ferrakaop approved these changes

2024-04-30 09:51 UTC, pdonohoe requested changes
Changes to view-templates/28.efx Results section should not be merged

2024-04-30 13:13 UTC, bertrand-lorentz commented
The changes to the "LotResult" section in view-templates/28.efx were reverted in commit ac1df69.

2024-04-30 14:31 UTC, pdonohoe approved these changes

2024-05-02 08:33 UTC, bertrand-lorentz approved these changes

2024-05-02 08:46 UTC, merged