Prepare release of SDK 1.7.4
OP-TED/eForms-SDK pull request #923
Opened 2024-04-29 13:01 UTC by bertrand-lorentz

The errors reported by the SDK Analyzer are expected.

I've checked the view templates locally with a modified analyzer, and no relevant errors were reported.

2024-04-29 20:24 UTC, ferrakaop approved these changes

2024-04-30 09:51 UTC, pdonohoe requested changes
Changes to view-templates/28.efx Results section should not be merged

2024-04-30 13:18 UTC, bertrand-lorentz commented
The changes to the "LotResult" section in view-templates/28.efx were reverted in commit e5d216a.

2024-04-30 14:34 UTC, pdonohoe approved these changes

2024-05-02 08:48 UTC, merged